# Generated by Django 3.0.8 on 2020-08-26 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itn', '0006_auto_20200826_0155'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='contact',
            managers=[
            ],
        ),
    ]
