# Generated by Django 3.0.8 on 2020-09-02 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itn', '0008_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
