# Generated by Django 3.0.8 on 2020-09-02 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itn', '0009_auto_20200902_1448'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
