# Generated by Django 3.0.8 on 2020-09-02 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itn', '0011_organization'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
